/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Detail: typeof import('./pages/Detail.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElText: typeof import('element-plus/es')['ElText']
    KLyric: typeof import('./components/KLyric.vue')['default']
    KSlider: typeof import('./components/KSlider.vue')['default']
    Library: typeof import('./pages/Library.vue')['default']
    Like: typeof import('./pages/Like.vue')['default']
    List: typeof import('./pages/List.vue')['default']
    Main: typeof import('./pages/Main.vue')['default']
    MainNav: typeof import('./components/MainNav.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./pages/Search.vue')['default']
    Setting: typeof import('./pages/Setting.vue')['default']
  }
}
