// DO NOT EDIT — generated by scripts/gen-ipc.mjs
import { ipcRenderer } from 'electron'

export const api = {
  db: {
    'addLibItem': (...args) => ipcRenderer.invoke('db:addLibItem', ...args),
    'delLibrary': (...args) => ipcRenderer.invoke('db:delLibrary', ...args),
    'delLibItem': (...args) => ipcRenderer.invoke('db:delLibItem', ...args),
    'getLibraries': (...args) => ipcRenderer.invoke('db:getLibraries', ...args),
    'getLibItems': (...args) => ipcRenderer.invoke('db:getLibItems', ...args),
    'searchLibItems': (...args) => ipcRenderer.invoke('db:searchLibItems', ...args),
    'addLibrary': (...args) => ipcRenderer.invoke('db:addLibrary', ...args),
    'onTransCreateCommonLib': (cb) => ipcRenderer.on('transCreateCommonLib', cb),
    'offTransCreateCommonLib': (cb) => ipcRenderer.removeListener('transCreateCommonLib', cb),
  },
  info: {
    'loadMusicLyrics': (...args) => ipcRenderer.invoke('info:loadMusicLyrics', ...args),
    'loadMusicInfo': (...args) => ipcRenderer.invoke('info:loadMusicInfo', ...args),
  },
  scan: {
    'getDirStruc': (...args) => ipcRenderer.invoke('scan:getDirStruc', ...args),
    'showItemInFolder': (...args) => ipcRenderer.invoke('scan:showItemInFolder', ...args),
  },
  win: {
    'openFileWindow': (...args) => ipcRenderer.invoke('win:openFileWindow', ...args),
    'openDirectoryWindow': (...args) => ipcRenderer.invoke('win:openDirectoryWindow', ...args),
    'minWindow': (...args) => ipcRenderer.invoke('win:minWindow', ...args),
    'maxWindow': (...args) => ipcRenderer.invoke('win:maxWindow', ...args),
    'closeWindow': (...args) => ipcRenderer.invoke('win:closeWindow', ...args),
    'reloadWindow': (...args) => ipcRenderer.invoke('win:reloadWindow', ...args),
    'openDevTools': (...args) => ipcRenderer.invoke('win:openDevTools', ...args),
  },
}
