// DO NOT EDIT — generated by scripts/gen-ipc.mjs
import type { IpcRendererEvent } from 'electron'
import type Database from 'better-sqlite3'
import type { ICommonTagsResult } from 'music-metadata'

export interface DbAPI {
  addLibItem(libID: number, libMode: LibMode, item: ILibItem): Promise<void>
  delLibrary(libID: number): Database.RunResult
  delLibItem(libID: number, itemID: number): Database.RunResult
  getLibraries(): Promise<ILibrary[]>
  getLibItems(libID: number): ILibItem[]
  searchLibItems(libID: number, keyword: string): ILibItem[]
  /** 添加总库表项和对应的表 */
  addLibrary(name: string, path: string, mode: LibMode): Promise<number>
  /** 曲库导入进度事件 @param inserted 已插入数量 @param total 总数量 */
  onTransCreateCommonLib(cb: (event: IpcRendererEvent, inserted: number, total: number) => void): void
  offTransCreateCommonLib(cb: (event: IpcRendererEvent, inserted: number, total: number) => void): void
}
export interface InfoAPI {
  /**
  * 读取音乐相关的歌词文件
  * @param path 音乐文件路径
  * @returns 歌词列表
  */
  loadMusicLyrics(path: string): Promise<ILyric[]>
  /**
  * 获取音乐文件的信息
  * @param path 音乐文件路径
  * @returns 音乐文件信息，包括标签和图片主色调
  */
  loadMusicInfo(path: string): Promise<{
    tag: ICommonTagsResult;
    mainColor: string;
}>
}
export interface ScanAPI {
  /**
  * 获取当前目录结构
  * @param path 目录路径
  * @returns 目录结构，包含目录名称、子目录列表和音乐列表
  */
  getDirStruc(path: string): Promise<IDir | undefined>
  /**
  * 在文件资源管理器中显示指定项目
  * @param path 文件路径
  */
  showItemInFolder(path: string): void
}
export interface WinAPI {
  /**
  * 打开文件对话框，选择音乐文件
  * @param window 将对话框作为模态窗口附加到父窗口
  * @returns 选择的音乐文件路径
  */
  openFileWindow(): Promise<string | undefined>
  /**
  * 打开文件对话框，选择文件夹
  * @param window 将对话框作为模态窗口附加到父窗口
  * @returns 选择的文件夹路径
  */
  openDirectoryWindow(): Promise<string | undefined>
  /** 最小化窗口 */
  minWindow(): void
  /** 最大化/还原窗口 */
  maxWindow(): void
  /** 关闭窗口 */
  closeWindow(): void
  /** 重载窗口 */
  reloadWindow(): void
  /** 打开开发者工具 */
  openDevTools(): void
}

export interface API {
  db: DbAPI
  info: InfoAPI
  scan: ScanAPI
  win: WinAPI
}
