/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KDetailBtn: typeof import('./../pages/PBar/components/KDetailBtn.vue')['default']
    KDialog: typeof import('./../components/KDialog.vue')['default']
    KDirInfo: typeof import('./../pages/PLibrary/components/KDirInfo.vue')['default']
    KDirList: typeof import('./../pages/PLibrary/components/KDirList.vue')['default']
    KDrawerBar: typeof import('./../pages/PBar/KDrawerBar.vue')['default']
    KDropdown: typeof import('./../components/KDropdown.vue')['default']
    KImage: typeof import('./../components/KImage.vue')['default']
    KLibDialog: typeof import('./../pages/PSetting/components/KLibDialog.vue')['default']
    KLibList: typeof import('./../components/KLibList.vue')['default']
    KLibSelect: typeof import('./../pages/PLibrary/components/KLibSelect.vue')['default']
    KLoopBtn: typeof import('./../pages/PBar/components/KLoopBtn.vue')['default']
    KLyric: typeof import('./../pages/PDetail/components/KLyric.vue')['default']
    KMenu: typeof import('./../directives/Menu/KMenu.vue')['default']
    KMusicBar: typeof import('./../pages/PBar/KMusicBar.vue')['default']
    KNavBar: typeof import('./../pages/PBar/KNavBar.vue')['default']
    KSelect: typeof import('./../components/KSelect.vue')['default']
    KSetting: typeof import('./../components/KSetting.vue')['default']
    KSlider: typeof import('./../components/KSlider.vue')['default']
    KTitleBar: typeof import('./../pages/PBar/KTitleBar.vue')['default']
    KTooltip: typeof import('./../directives/Tooltip/KTooltip.vue')['default']
    PDetail: typeof import('./../pages/PDetail/PDetail.vue')['default']
    PLibrary: typeof import('./../pages/PLibrary/PLibrary.vue')['default']
    PLike: typeof import('./../pages/PLike/PLike.vue')['default']
    PList: typeof import('./../pages/PList/PList.vue')['default']
    PSearch: typeof import('./../pages/PSearch/PSearch.vue')['default']
    PSetting: typeof import('./../pages/PSetting/PSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
