/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Detail: typeof import('./../pages/Detail.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElText: typeof import('element-plus/es')['ElText']
    KDetailBtn: typeof import('./../components/KDetailBtn.vue')['default']
    KLyric: typeof import('./../components/KLyric.vue')['default']
    KMenu: typeof import('./../directives/Menu/KMenu.vue')['default']
    KMusicBar: typeof import('./../components/KMusicBar.vue')['default']
    KSlider: typeof import('./../components/KSlider.vue')['default']
    KTitleBar: typeof import('./../components/KTitleBar.vue')['default']
    KTooltip: typeof import('./../directives/Tooltip/KTooltip.vue')['default']
    Library: typeof import('./../pages/Library.vue')['default']
    Like: typeof import('./../pages/Like.vue')['default']
    List: typeof import('./../pages/List.vue')['default']
    Main: typeof import('./../pages/Main.vue')['default']
    MainNav: typeof import('./../components/MainNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../pages/Search.vue')['default']
    Setting: typeof import('./../pages/Setting.vue')['default']
  }
}
