/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    KDetailBtn: typeof import('./../components/KDetailBtn.vue')['default']
    KDirList: typeof import('./../components/KDirList.vue')['default']
    KLibList: typeof import('./../components/KLibList.vue')['default']
    KLyric: typeof import('./../components/KLyric.vue')['default']
    KMenu: typeof import('./../directives/Menu/KMenu.vue')['default']
    KMusicBar: typeof import('./../components/KMusicBar.vue')['default']
    KNavBar: typeof import('./../components/KNavBar.vue')['default']
    KSettingItem: typeof import('./../components/KSettingItem.vue')['default']
    KSlider: typeof import('./../components/KSlider.vue')['default']
    KTitleBar: typeof import('./../components/KTitleBar.vue')['default']
    KTooltip: typeof import('./../directives/Tooltip/KTooltip.vue')['default']
    PDetail: typeof import('./../pages/PDetail.vue')['default']
    PLibrary: typeof import('./../pages/PLibrary.vue')['default']
    PLike: typeof import('./../pages/PLike.vue')['default']
    PList: typeof import('./../pages/PList.vue')['default']
    PMain: typeof import('./../pages/PMain.vue')['default']
    PSearch: typeof import('./../pages/PSearch.vue')['default']
    PSetting: typeof import('./../pages/PSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
